---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: c01
          image: sekhar295/health-care:1.0
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: healthcare
